name: Rails CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install bundler
        run: |
          bundle install
      - name: Rubocop
        run: bundle exec rubocop
      - name: Rails Best Practices
        run: bundle exec rails_best_practices -e "db/schema.rb,db/migrate,vendor,app/models/application_record.rb"
      - name: Rpec
        run: bundle exec rspec --format documentation
